apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config-files
  namespace: cluster0-operators
data:
  redis.yaml: |
    apiVersion: redis.redis.opstreelabs.in/v1beta1
    kind: Redis
    metadata:
      name: redis-standalone
      namespace: openshift-redis
    spec:
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      kubernetesConfig:
        image: 'quay.io/opstree/redis:v7.0.5'
        imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      redisExporter:
        enabled: true
        image: 'quay.io/opstree/redis-exporter:v1.44.0'
        imagePullPolicy: IfNotPresent