---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster0-operators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster0-operators
  namespace: cluster0-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster0-operators-cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster0-operators
  namespace: cluster0-operators
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-install-files
  namespace: cluster0-operators
data:
  lso.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-local-storage
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: local-storage-operator-operatorgroup
      namespace: openshift-local-storage
    spec:
      targetNamespaces:
      - openshift-local-storage
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: local-storage-operator
      namespace: openshift-local-storage
    spec:
      channel: "stable"
      name: local-storage-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  sriov.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-sriov-network-operator
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: sriov-network-operator-operatorgroup
      namespace: openshift-sriov-network-operator
    spec:
      targetNamespaces:
      - openshift-sriov-network-operator
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: sriov-network-operator
      namespace: openshift-sriov-network-operator
    spec:
      channel: "stable"
      name: sriov-network-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
  ptp.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-ptp
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ptp-operator-operatorgroup
      namespace: openshift-ptp
    spec:
      targetNamespaces:
      - openshift-ptp
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ptp-operator
      namespace: openshift-ptp
    spec:
      channel: "stable"
      name: ptp-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config-files
  namespace: cluster0-operators
data:
  lso.yaml: |
    apiVersion: local.storage.openshift.io/v1
    kind: LocalVolume
    metadata:
      name: fs
      namespace: openshift-local-storage
    spec:
      logLevel: Normal
      managementState: Managed
      storageClassDevices:
        - devicePaths:
            - /dev/vdb
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cluster0-operators
  name: cluster0-operators
  namespace: cluster0-operators
spec:
  serviceAccountName: cluster0-operators
  containers:
    - image: quay.io/mavazque/cluster0-operators:latest
      name: cluster0-operators
      args:
      - run
      - -i
      - /var/tmp/operator-install-manifests
      - -c
      - /var/tmp/operator-config-manifests
      volumeMounts:
      - name: operator-install-manifests
        mountPath: /var/tmp/operator-install-manifests/
      - name: operator-config-manifests
        mountPath: /var/tmp/operator-config-manifests/
  volumes:
    - name: operator-install-manifests
      configMap:
        name: operator-install-files
    - name: operator-config-manifests
      configMap:
        name: operator-config-files