---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster0-operators-cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster0-operators
  namespace: cluster0-operators
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io