apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-install-files
  namespace: cluster0-operators
data:
  00_lvmso.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-storage
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: lvms-operator-operatorgroup
      namespace: openshift-storage
    spec:
      targetNamespaces:
      - openshift-storage
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: lvms-operator
      namespace: openshift-storage
    spec:
      channel: "stable-4.12"
      name: lvms-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
  01_rhacm.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: open-cluster-management
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: advanced-cluster-management-operatorgroup
      namespace: open-cluster-management
    spec:
      targetNamespaces:
      - open-cluster-management
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: advanced-cluster-management
      namespace: open-cluster-management
    spec:
      channel: "release-2.7"
      name: advanced-cluster-management
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
  02_mce.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: multicluster-engine
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: multicluster-engine-operatorgroup
      namespace: multicluster-engine
    spec:
      targetNamespaces:
      - multicluster-engine
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: multicluster-engine
      namespace: multicluster-engine
    spec:
      channel: "stable-2.2"
      name: multicluster-engine
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
  03_openshift_gitops.yaml: |
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: openshift-gitops-operator
      namespace: openshift-operators
    spec:
      channel: "latest"
      name: openshift-gitops-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
  04_talm.yaml: |
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: topology-aware-lifecycle-manager
      namespace: openshift-operators
    spec:
      channel: "stable"
      name: topology-aware-lifecycle-manager
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
