apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-install-files
  namespace: cluster0-operators
data:
  lso.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-local-storage
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: local-storage-operator-operatorgroup
      namespace: openshift-local-storage
    spec:
      targetNamespaces:
      - openshift-local-storage
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: local-storage-operator
      namespace: openshift-local-storage
    spec:
      channel: "stable"
      name: local-storage-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
  sriov.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-sriov-network-operator
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: sriov-network-operator-operatorgroup
      namespace: openshift-sriov-network-operator
    spec:
      targetNamespaces:
      - openshift-sriov-network-operator
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: sriov-network-operator
      namespace: openshift-sriov-network-operator
    spec:
      channel: "stable"
      name: sriov-network-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
  ptp.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: openshift-ptp
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        workload.openshift.io/allowed: management
    ---
    apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ptp-operator-operatorgroup
      namespace: openshift-ptp
    spec:
      targetNamespaces:
      - openshift-ptp
    ---
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ptp-operator
      namespace: openshift-ptp
    spec:
      channel: "stable"
      name: ptp-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic
