apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config-files
  namespace: cluster0-operators
data:
  lso.yaml: |
    apiVersion: local.storage.openshift.io/v1
    kind: LocalVolume
    metadata:
      name: fs
      namespace: openshift-local-storage
    spec:
      logLevel: Normal
      managementState: Managed
      storageClassDevices:
        - devicePaths:
            - /dev/vdb
